### ISSUE TITLE
Implement columns block correct breakpoints

### ISSUE THREAD

**Issue by alexcarol** [Esri/esri-eds#196]
Migrated from: https://github.com/aemsites/esri/issues/72
  
  Original: https://www.esri.com/en-us/about/about-esri/mea-central-asia#esri-events
New: https://main--esri-eds--esri.aem.page/en-us/about/about-esri/mea-central-asia

![image](https://github.com/user-attachments/assets/72ee7d93-f914-4908-9b5d-f60b76e132e9)

**Comment by twhite313** [comment]
image should be on bottom in mobile/tablet
check image size -- should fill half, not scale image down

**Comment by ahenriksen-fedx** [comment]
@twhite313 this problem was resolved with PR #303. Can you please confirm?
