### ISSUE TITLE
Missing visual issues

### ISSUE THREAD

**Issue by alexcarol** [Esri/esri-eds#253]
- [x] #255
- [x] #254
- [x] PR#256 Set background color to #2b2b2b for calcite-mode-dark main (https://main--esri-eds--esri.aem.page/fr-fr/about/about-esri/overview#d%C3%A9veloppement-durable)
![image](https://github.com/user-attachments/assets/1644e337-c534-490b-95c0-08e02796987d)

- [x] Fix call to action second button to have the alternative style (https://main--esri-eds--esri.aem.page/fr-fr/about/about-esri/overview). Addressing with #277

**Comment by twhite313** [comment]
Button alt styles, `aem.js` has `primary | secondary` options based on `strong | em`. Is that carrying over? I think this is a good pattern to follow.

**Comment by twhite313** [comment]
RE: button styling. Using `strong | em` does work, with limits right now.

But I've noticed that some block where brought over and kept the `<calcite-button>` in tact. Any reason we didn't do that for all buttons?

**Comment by alexcarol** [comment]
> RE: button styling. Using `strong | em` does work, with limits right now.
> 
> But I've noticed that some block where brought over and kept the `<calcite-button>` in tact. Any reason we didn't do that for all buttons?

There's logic in some blocks that does the conversion, maybe we can discuss those blocks and see what we want to do with them.

**Comment by twhite313** [comment]
CTA second button alternative style is ready, but relies on some content changes.
