### ISSUE TITLE
Storyteller video fixes

### ISSUE THREAD

**Issue by alexcarol** [Esri/esri-eds#254]
- [ ] The video should only autoplay once (without looping)
- [ ] Video button should have a different style

Both of those issues might be solved by using a "video" tag.

https://main--esri-eds--esri.aem.page/fr-fr/about/about-esri/overview
![image](https://github.com/user-attachments/assets/efc117ca-791b-432e-bff4-9186acb7401d)

https://www.esri.com/fr-fr/about/about-esri/overview
![image](https://github.com/user-attachments/assets/2b3b806f-9d71-48cd-ada9-65cb8d3e88e0)

**Comment by twhite313** [comment]
@jsavella can you look at this? Just might need some of the latest video code you have.

**Comment by jsavella** [comment]
> @jsavella can you look at this? Just might need some of the latest video code you have.

I'll take a look.

**Comment by anu13297** [comment]
@jsavella can you also please fix the overflowing content container over the foreground video?
