### ISSUE TITLE
About page hero should have a max-height

### ISSUE THREAD

**Issue by alexcarol** [Esri/esri-eds#255]
Current: https://main--esri-eds--esri.aem.page/fr-fr/about/about-esri/overview
Live: https://www.esri.com/fr-fr/about/about-esri/overview

**Comment by twhite313** [comment]
Does't need max-height so much as content | image sections need to be aligned better. 
Wonder if it wouldn't be better to switch to `grid` and set up some template areas?

**Comment by alexcarol** [comment]
> Does't need max-height so much as content | image sections need to be aligned better. Wonder if it wouldn't be better to switch to `grid` and set up some template areas?

I think there's two different issues that we're discussing, one is that in regular displays the grid is slightly different:
EDS:
![image](https://github.com/user-attachments/assets/a4f4b257-143a-495b-9da1-4f9bc564f8a0)
Live:
![image](https://github.com/user-attachments/assets/ccff406b-fd9e-47c7-9a34-c6b3ce6fcf51)


The issue mentioned here is that on wider displays the height is limited on the live site:
EDS:
![image](https://github.com/user-attachments/assets/6f1e7008-757e-4716-bd84-d1a4bb8b193b)

Live:
![image](https://github.com/user-attachments/assets/7f5420a8-d72e-4cb1-9422-0f4d272d4683)


In any case, both issues should be addressed.
