### ISSUE TITLE
Upload and style SVG icons

### ISSUE THREAD

**Issue by anu13297** [Esri/esri-eds#266]
Upload and style SVG icons for text link stack iocn component equivalent.

Live: https://www.esri.com/en-us/about/about-esri/company, https://www.esri.com/en-us/about/about-esri/europe/overview
Test: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/company, https://main--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview

Live:
![Screenshot 2024-10-29 at 7 33 38 PM](https://github.com/user-attachments/assets/15ad7091-c202-4115-9f44-bdeec62a2dd8)

EDS:
![Screenshot 2024-10-29 at 7 33 44 PM](https://github.com/user-attachments/assets/3978ca8c-cc93-4f89-ab4c-4b6937732398)

**Comment by twhite313** [comment]
Icons coming across -- might not be the correct ones right now -- adding styles to account for sizes.
