### ISSUE TITLE
Elastic content strip - images broken and hover color update

### ISSUE THREAD

**Issue by anu13297** [Esri/esri-eds#268]
Elastic content strip - Images(icons) are broken on the page mentioned below. On hover, the box shadow color does not match with prod.

Live: https://www.esri.com/en-us/about/about-esri/europe/overview
EDS: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview

Live:
![Screenshot 2024-10-29 at 7 57 35 PM](https://github.com/user-attachments/assets/6ac4d2eb-433f-4aba-95b0-5b33ff67ad96)

EDS:
![Screenshot 2024-10-29 at 7 57 42 PM](https://github.com/user-attachments/assets/0d2310c1-92e6-4fee-a2f0-235cca404f5d)

**Comment by ahenriksen-fedx** [comment]
This issue appears to be resolved. Closing.
