### ISSUE TITLE
Story Teller - Icons missing

### ISSUE THREAD

**Issue by anu13297** [Esri/esri-eds#273]
Icons missing on story teller component content section.

Live: https://www.esri.com/en-us/artificial-intelligence/overview
EDS: https://main--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview

Live: 
![Screenshot 2024-10-30 at 2 59 38 PM](https://github.com/user-attachments/assets/76569297-a213-4920-aebb-0dd720babbdf)

EDS: 
![Screenshot 2024-10-30 at 2 59 32 PM](https://github.com/user-attachments/assets/d506e283-88d2-4e25-a526-49e95def418b)

**Comment by twhite313** [comment]
@alexcarol icons not in the import. Looks like the original problem with inlined icons -- there is no name reference to pull in. Not sure what the solution is. Probably manual updates at this point.
