### ISSUE TITLE
Storyteller button alignment

### ISSUE THREAD

**Issue by twhite313** [Esri/esri-eds#299]
Versions with the content on the left, the text alignment is off. 

- the button is at screens edge
- Title is to the right under picture

https://main--esri-eds--esri.aem.live/en-us/about/about-esri/overview#we-make-the-worlds-most-powerful-gis-software

**Comment by ahenriksen-fedx** [comment]
@twhite313 - I will work on this issue.

**Comment by ahenriksen-fedx** [comment]
@twhite313 - This issue appears to have been resolved already. Closing.
