### ISSUE TITLE
Needs media-split block for blocks under Purpose Build Apps

### ISSUE THREAD

**Issue by twhite313** [Esri/esri-eds#334]
https://www.esri.com/en-us/capabilities/field-operations/overview#:~:text=behind%20your%20firewall.-,Plan,-Get%20the%20office

Doc just lists them as content with no structure.

**Comment by alexcarol** [comment]
> https://www.esri.com/en-us/capabilities/field-operations/overview#:~:text=behind%20your%20firewall.-,Plan,-Get%20the%20office

Import done, the block will need further styling
