### ISSUE TITLE
Local Navigation No Background When Sticky

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#343]
When local nav becomes sticky, there is no background or background does not sticky with local nav.  

Maybe corrected with @twhite313 update to local nav in header block. https://github.com/Esri/esri-eds/issues/341

http://localhost:3000/en-us/about/about-esri/overview

![mobilesticky](https://github.com/user-attachments/assets/06934b3c-f28c-4460-8634-b7ba454199db)

![localsticks](https://github.com/user-attachments/assets/b3d66edd-d811-4d97-ba74-80b84665a856)

**Comment by twhite313** [comment]
Also, variation on it  from Field Ops
https://main--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
![field-op nav](https://github.com/user-attachments/assets/a7a5f321-b15e-4657-8420-d3a6df912da2)

**Comment by twhite313** [comment]
Looks to be resolved with recent updates.
