### ISSUE TITLE
HERO BANNER: Implement Hero Banner Variant MEDIUM

### ISSUE THREAD

**Issue by jsavella** [Esri/esri-eds#434]

**Comment by jsavella** [comment]
@twhite313 Do we care to work on a MEDIUM variant for HERO Banner?

https://www.esri.com/en-us/capabilities/mapping/overview (hero banner medium variant example)
https://main--esri-eds--esri.aem.live/en-us/capabilities/mapping/overview

**Comment by twhite313** [comment]
I'm not worried about supporting all of the possible options. Let's just make sure that what we have matches the live page
